### ISSUE TITLE
Can't swipe to autosuggest field in Firefox with Samsung's Voice Assistant

### ISSUE THREAD

**Issue by robfentress** [weboverhauls/demos#11]
In testing with Samsung Voice Assistant on Mobile Firefox, I find I can't access the autosuggest box using swipe gestures. It skips from the label directly to the submit button.  In Samsung's Internet app it does let me get to it by swiping.   However, I still need to explore by touch to access the options that appear.

**Comment by weboverhauls** [comment]
Sorry it's not working as expected for you. Technically I consider this a user-agent bug (support lacking in the browser and/or the screen reader) as the code is written to W3C specification. But I'm glad you bring this up; it's even more reason why native form elements should always be used, which is mentioned in my [Web Axe blog post](http://www.webaxe.org/accessible-custom-select-dropdowns/). This autosuggest demo tries its hardest to make accessible what designers dream up. Cheers.
